Feat/modem db 2.0.1
NordicSemiconductor/pc-nrfconnect-cellularmonitor pull request #435
Opened 2024-07-09 08:55 UTC by kylebonnici

2024-10-18 14:29 UTC, KievDevel commented on Changelog.md
> +## 2.4.1 - 2024-07-09
unreleased I assume
```suggestion
## 2.4.3 - unreleased
```

2024-10-18 14:30 UTC, KievDevel commented
Does it overlap with https://github.com/NordicSemiconductor/pc-nrfconnect-cellularmonitor/releases/tag/v2.4.1?

2024-12-13 10:27 UTC, greg-fer requested changes

2024-12-13 10:27 UTC, greg-fer commented on Changelog.md
> +    v2.0.1, v2.0.1-FOTA, v2.0.2 and v2.0.2-FOTA.
```suggestion
-   Pre-bundled Modem Trace Databases: v1.3.6, v1.3.6-FOTA, v1.3.7, v1.3.7-FOTA,
    v2.0.1, v2.0.1-FOTA, v2.0.2, and v2.0.2-FOTA.
```

2024-12-13 10:27 UTC, greg-fer commented on Changelog.md
> +-   Modem Trace Database dropdown filters out unsupported DB for nRF9151.
```suggestion
-   Issue where the Modem Trace Database's drop-down would filter out an unsupported database for nRF9151.
```
How is filtering out an _unsupported_ db an issue? Sounds logical to me to filter out something that is not supported.

2024-12-13 10:43 UTC, greg-fer approved these changes

2024-12-16 16:17 UTC, KievDevel commented on Changelog.md
>  ## 2.4.3 - unreleased
```suggestion
## 2.4.3 - 2024-12-17
```

2024-12-16 16:21 UTC, merged